# Generated by Django 2.0.1 on 2020-06-25 14:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import s3direct.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0095_auto_20200625_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from='title', unique=True)),
                ('description', models.TextField()),
                ('image', s3direct.fields.S3DirectField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('capacity', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('started', 'Started'), ('in progress', 'InProgress'), ('finished', 'Finished')], default='upcoming', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='profiles.TeacherProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
