# Generated by Django 2.0.1 on 2020-07-01 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0002_auto_20200701_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupcategory',
            old_name='Enabled',
            new_name='enabled',
        ),
    ]
