# Generated by Django 2.0.1 on 2020-07-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0005_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default='2020-05-05'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, default='2020-05-05'),
        ),
    ]
