# Generated by Django 2.0.1 on 2020-07-02 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0006_auto_20200702_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='group_courses.Course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
