# Generated by Django 2.0.1 on 2020-07-06 08:42

from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0007_auto_20200702_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('description', models.TextField()),
                ('document', s3direct.fields.S3DirectField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='group_courses.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
