# Generated by Django 2.0.1 on 2020-07-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0010_reting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reting',
            new_name='Rating',
        ),
    ]
