# Generated by Django 2.0.1 on 2020-07-08 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0011_auto_20200708_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('total_score', models.IntegerField()),
                ('finished', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='group_courses.Assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
