# Generated by Django 2.0.1 on 2020-07-09 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0095_auto_20200625_1735'),
        ('group_courses', '0013_groupquizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='profiles.StudentProfile'),
        ),
    ]
