# Generated by Django 2.0.1 on 2020-07-09 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0014_rating_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='number_of_stars',
        ),
        migrations.AddField(
            model_name='rating',
            name='customer_service',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Customer Service'),
        ),
        migrations.AddField(
            model_name='rating',
            name='ease_of_use',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Ease of use'),
        ),
        migrations.AddField(
            model_name='rating',
            name='likehihood_to_recommend',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Likehihood to recommend'),
        ),
        migrations.AddField(
            model_name='rating',
            name='met_learning_objectives',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Met Learning Objectives'),
        ),
        migrations.AddField(
            model_name='rating',
            name='rating_weight',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='rating',
            name='supporting_materials',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Supporting Materials'),
        ),
        migrations.AddField(
            model_name='rating',
            name='teacher',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Teacher'),
        ),
        migrations.AddField(
            model_name='rating',
            name='value_for_money',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Value for money'),
        ),
    ]
