# Generated by Django 2.0.1 on 2020-07-09 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0015_auto_20200709_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_valid', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('quiz_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='group_courses.GroupQuizQuestion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
