# Generated by Django 2.0.1 on 2020-07-09 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0095_auto_20200625_1735'),
        ('group_courses', '0016_groupchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='group_courses.GroupChoice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='profiles.StudentProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
