# Generated by Django 2.0.1 on 2020-07-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0017_groupanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupquizquestion',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
