# Generated by Django 2.0.1 on 2020-07-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0017_groupanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='file_path_within_bucket',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
