# Generated by Django 2.0.1 on 2020-07-21 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0017_groupanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupcategory',
            options={'verbose_name_plural': 'Group categories'},
        ),
    ]
