# Generated by Django 2.0.1 on 2020-07-14 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0018_groupquizquestion_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupquizquestion',
            options={'ordering': ['order']},
        ),
    ]
