# Generated by Django 2.0.1 on 2020-07-15 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0019_auto_20200714_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupquiz',
            name='duration',
            field=models.IntegerField(default=60, help_text='Minutes', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
