# Generated by Django 2.0.1 on 2020-07-16 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0018_material_file_path_within_bucket'),
        ('group_courses', '0020_groupquiz_duration'),
    ]

    operations = [
    ]
