# Generated by Django 2.0.1 on 2020-07-22 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0021_merge_20200716_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_weight',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
