# Generated by Django 2.0.1 on 2020-07-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0022_auto_20200722_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file_path_within_bucket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
