# Generated by Django 2.0.1 on 2020-07-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0018_auto_20200722_0043'),
        ('group_courses', '0023_auto_20200722_0936'),
    ]

    operations = [
    ]
