# Generated by Django 2.0.1 on 2020-08-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0024_merge_20200722_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_adaptive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('all_levels', 'ALL LEVELS'), ('beginner', 'BEGINNER'), ('intermediate', 'INTERMEDIATE'), ('advanced', 'ADVANCED')], default='all_levels', max_length=20),
        ),
    ]
