# Generated by Django 2.0.1 on 2020-08-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0026_testcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='test_drive',
            field=models.BooleanField(default=False),
        ),
    ]
