# Generated by Django 2.0.1 on 2020-08-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0027_course_test_drive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupquiz',
            options={'verbose_name_plural': 'Group quizzes'},
        ),
        migrations.AddField(
            model_name='material',
            name='gmat',
            field=models.CharField(blank=True, choices=[('analytical_writing_assessment', 'Analytical Writing Assessment'), ('integrated_reasoning', 'Integrated Reasoning'), ('quantitative_reasoning', 'Quantitative Reasoning'), ('verbal_reasoning', 'Verbal Reasoning')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='gre',
            field=models.CharField(blank=True, choices=[('analytical_writing', 'Analytical Writing'), ('quantitative_reasoning', 'Quantitative Reasoning'), ('verbal_reasoning', 'Verbal Reasoning')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='sat',
            field=models.CharField(blank=True, choices=[('essay', 'Essay'), ('math', 'Math'), ('reading', 'Reading'), ('writing_and_language', 'Writing and Language')], max_length=100, null=True),
        ),
    ]
