# Generated by Django 2.0.1 on 2020-08-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0027_course_test_drive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='valid_until',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
