# Generated by Django 2.0.1 on 2020-08-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0028_auto_20200814_1321'),
        ('group_courses', '0028_auto_20200813_1331'),
    ]

    operations = [
    ]
