# Generated by Django 2.0.1 on 2020-08-17 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0030_assistant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_weight',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Rating'),
        ),
    ]
