# Generated by Django 2.0.1 on 2020-08-17 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0096_subscribedtutors'),
        ('group_courses', '0031_auto_20200817_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistant',
            name='course',
        ),
        migrations.RemoveField(
            model_name='assistant',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='assistant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant', to='profiles.TeacherProfile'),
        ),
        migrations.DeleteModel(
            name='Assistant',
        ),
    ]
