# Generated by Django 2.0.1 on 2020-08-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0033_auto_20200818_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchoice',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Correct'),
        ),
        migrations.AlterField(
            model_name='groupquizquestion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
