# Generated by Django 2.0.1 on 2020-08-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0034_auto_20200819_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchoice',
            options={'verbose_name': 'Choice', 'verbose_name_plural': 'Choices'},
        ),
        migrations.AlterModelOptions(
            name='groupquiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='groupquizquestion',
            options={'ordering': ['order'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
