# Generated by Django 2.0.1 on 2020-08-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0035_auto_20200820_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupquizquestion',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Question Description'),
        ),
    ]
