# Generated by Django 2.0.1 on 2020-09-04 13:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0037_auto_20200821_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='Minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Session',
            },
        ),
        migrations.AlterModelOptions(
            name='testcourse',
            options={'verbose_name_plural': 'Test Course'},
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='start_date',
        ),
        migrations.AddField(
            model_name='session',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='group_courses.Lecture'),
        ),
    ]
