# Generated by Django 2.0.1 on 2020-09-04 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0097_auto_20200821_1451'),
        ('group_courses', '0038_auto_20200904_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Session_student',
            },
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterField(
            model_name='session',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='group_courses.Lecture'),
        ),
        migrations.AddField(
            model_name='sessionstudent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_student', to='group_courses.Session'),
        ),
        migrations.AddField(
            model_name='sessionstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_student', to='profiles.StudentProfile'),
        ),
    ]
