# Generated by Django 2.0.1 on 2020-09-11 09:26

from django.db import migrations, models
import edutailors.apps.group_courses.models


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0040_session_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.CharField(default=edutailors.apps.group_courses.models.get_random_id, editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
