# Generated by Django 2.0.1 on 2020-09-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0041_auto_20200910_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='passed_diagnostic',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='diagnostic_status',
            field=models.CharField(choices=[('not_started', 'NOT STARTED'), ('in_progress', 'IN PROGRESS'), ('completed', 'COMPLETED')], default='not_started', max_length=100),
        ),
        migrations.RemoveField(
            model_name='diagnostictestquiz',
            name='course',
        ),
        migrations.AddField(
            model_name='diagnostictestquiz',
            name='course',
            field=models.ManyToManyField(related_name='diagnostic_test_quiz', to='group_courses.Course'),
        ),
    ]
