# Generated by Django 2.0.1 on 2020-09-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0042_auto_20200910_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostictestquiz',
            name='total_score',
        ),
    ]
