# Generated by Django 2.0.1 on 2020-09-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0043_remove_diagnostictestquiz_total_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostictestquiz',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='diagnostic_test_quiz',
            field=models.ManyToManyField(related_name='courses', to='group_courses.DiagnosticTestQuiz'),
        ),
    ]
