# Generated by Django 2.0.1 on 2020-09-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0040_session_description'),
        ('group_courses', '0044_auto_20200910_1603'),
    ]

    operations = [
    ]
