# Generated by Django 2.0.1 on 2020-09-11 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0041_auto_20200911_1226'),
        ('group_courses', '0045_merge_20200910_2004'),
    ]

    operations = [
    ]
