# Generated by Django 2.0.1 on 2020-09-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0045_merge_20200910_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnostictestchoice',
            options={'verbose_name': 'Diagnostic Test Choice', 'verbose_name_plural': 'Diagnostic Test Choices'},
        ),
        migrations.AlterModelOptions(
            name='diagnostictestquestion',
            options={'ordering': ['order'], 'verbose_name': 'Diagnostic Test Question', 'verbose_name_plural': 'Diagnostic Test Questions'},
        ),
        migrations.AlterModelOptions(
            name='diagnostictestquiz',
            options={'verbose_name': 'Diagnostic Test Quiz', 'verbose_name_plural': 'Diagnostic Test Quizzes'},
        ),
    ]
