# Generated by Django 2.0.1 on 2020-09-11 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0046_auto_20200911_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostictestquestion',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
