# Generated by Django 2.0.1 on 2020-09-11 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0047_auto_20200911_1147'),
        ('group_courses', '0046_merge_20200911_1234'),
    ]

    operations = [
    ]
