# Generated by Django 2.0.1 on 2020-09-11 12:54

from django.db import migrations


# Create Diagnostic Test Quiz for old courses on production
def create_diagnostic_test(apps, schema_editor):
    DiagnosticTestQuiz = apps.get_model("group_courses", "DiagnosticTestQuiz")
    db_alias = schema_editor.connection.alias
    DiagnosticTestQuiz.objects.using(db_alias).create(
        title="DiagnosticTestQuiz", id=1000000
    )

def delete_diagnostic_test(apps, schema_editor):
    DiagnosticTestQuiz = apps.get_model("group_courses", "DiagnosticTestQuiz")
    db_alias = schema_editor.connection.alias
    DiagnosticTestQuiz.objects.using(db_alias).filter(
        id=1000000).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0048_merge_20200911_1554'),
    ]

    operations = [
        migrations.RunPython(create_diagnostic_test, delete_diagnostic_test),
    ]
