# Generated by Django 2.0.1 on 2020-09-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0050_auto_20200914_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnostictestquiz',
            options={'verbose_name': 'Diagnostic Test Quiz', 'verbose_name_plural': 'Diagnostic Test Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name_plural': 'Course Content'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name_plural': 'Course Lecture Sessions'},
        ),
        migrations.AddField(
            model_name='material',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnostictestquestion',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
