# Generated by Django 2.0.1 on 2020-09-18 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0097_auto_20200821_1451'),
        ('group_courses', '0051_auto_20200914_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Assessment Answers',
            },
        ),
        migrations.CreateModel(
            name='AssessmentChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_valid', models.BooleanField(default=True, verbose_name='Correct')),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Question Description')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='diagnostictestanswer',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='diagnostictestanswer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='diagnostictestchoice',
            name='test_question',
        ),
        migrations.RemoveField(
            model_name='diagnostictestquestion',
            name='test_quiz',
        ),
        migrations.RemoveField(
            model_name='groupanswer',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='groupanswer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='groupchoice',
            name='quiz_question',
        ),
        migrations.RemoveField(
            model_name='groupquiz',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='groupquizquestion',
            name='group_quiz',
        ),
        migrations.AlterModelOptions(
            name='assessment',
            options={'verbose_name': 'Assessment', 'verbose_name_plural': 'Assessments'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='diagnostic_test_quiz',
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('diagnostic', 'Diagnostic'), ('quiz', 'Quiz'), ('midterm_exam', 'Midterm Exam'), ('final_exam', 'Final Exam')], default='quiz', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='total_score',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='DiagnosticTestAnswer',
        ),
        migrations.DeleteModel(
            name='DiagnosticTestChoice',
        ),
        migrations.DeleteModel(
            name='DiagnosticTestQuestion',
        ),
        migrations.DeleteModel(
            name='DiagnosticTestQuiz',
        ),
        migrations.DeleteModel(
            name='GroupAnswer',
        ),
        migrations.DeleteModel(
            name='GroupChoice',
        ),
        migrations.DeleteModel(
            name='GroupQuiz',
        ),
        migrations.DeleteModel(
            name='GroupQuizQuestion',
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='group_courses.Assessment'),
        ),
        migrations.AddField(
            model_name='assessmentchoice',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='group_courses.AssessmentQuestion'),
        ),
        migrations.AddField(
            model_name='assessmentanswer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='group_courses.AssessmentChoice'),
        ),
        migrations.AddField(
            model_name='assessmentanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='profiles.StudentProfile'),
        ),
    ]
