# Generated by Django 2.0.1 on 2020-09-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0052_auto_20200918_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='finished',
        ),
    ]
