# Generated by Django 2.0.1 on 2020-09-23 15:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0097_auto_20200821_1451'),
        ('group_courses', '0054_auto_20200922_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_score', to='group_courses.Assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_score', to='profiles.StudentProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
