# Generated by Django 2.0.1 on 2020-11-04 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_lists', '0034_auto_20201028_1354'),
        ('group_courses', '0056_auto_20200923_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='education_lists.Subject'),
        ),
        migrations.AlterField(
            model_name='testcourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcourse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GroupCategory',
        ),
    ]
