# Generated by Django 2.0.1 on 2020-11-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_courses', '0057_auto_20201104_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['created', 'updated'], 'verbose_name_plural': 'Course Lectures'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['end_date'], 'verbose_name_plural': 'Course Lecture Sessions'},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course_rated',
            field=models.BooleanField(default=False),
        ),
    ]
